django/practice_project/config/app/urls.py
from django.urls import path
from . import views

app_name='app'

urlpatterns = [
    path('employees/', views.EmployeeListView.as_view(),name='employees'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(),name='employee'),
    path('employees/create/', views.EmployeeCreateView.as_view(),name='create'),
    path('employees/update/<int:pk>/', views.EmployeeUpdateView.as_view(),name='update'),
    path('employees/delete/<int:pk>/', views.EmployeeDeleteView.as_view(),name='delete'),

    path('departments/', views.DepartmentListView.as_view(),name='departments'),
    path('departments/<int:pk>/', views.DepartmentDetailView.as_view(),name='department'),
]

django/practice_project/config/config/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(),name='home'),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

django/practice_project/config/app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Employee(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=20)
    department = models.ForeignKey(Department,related_name='employees',on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app:employee',kwargs={'pk':self.pk})

django/practice_project/config/app/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
from django.urls import reverse_lazy

# Create your views here.

# Employees
class EmployeeListView(ListView):
    context_object_name = 'employees'
    model = models.Employee


class EmployeeDetailView(DetailView):
    # context_object_name = 'employee_detail'
    model = models.Employee
    template_name ='app/employee_detail.html'


class EmployeeCreateView(CreateView):
    model = models.Employee
    fields = ('name','email','phone','department')


class EmployeeUpdateView(UpdateView):
    model = models.Employee
    fields = ('name','email','phone','department')


class EmployeeDeleteView(DeleteView):
    model = models.Employee
    success_url = reverse_lazy('app:employees')


# Departments
class DepartmentListView(ListView):
    context_object_name = 'departments'
    model = models.Department


class DepartmentDetailView(DetailView):
    # context_object_name = 'employee_detail'
    model = models.Department
    template_name = 'app/department_detail.html'

django/practice_project/config/config/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context =super().get_context_data(**kwargs)
        context['home_desc'] = 'This is just to demonstrate content injection'
        return context

django/practice_project/config/app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="text-center">

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand"><a class="nav-link active" href="{% url 'home' %}">DJANGO</a></h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'app:employees' %}">Employees</a>
                <a class="nav-link" href="{% url 'app:departments' %}">Departments</a>
                <a class="nav-link" href="#">Login</a>
                <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>
            </nav>
        </div>
    </header>
        {% block content %}

        {% endblock content %}
    <footer class="mastfoot mt-auto">
        <div class="inner">
            <p>Developed by <a href="http://mmaruf.herokuapp.com/" target="_blank">Maruf</a>.</p>
        </div>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

django/practice_project/config/app/templates/app/department_detail.html
{% extends 'app/base.html' %}

{% block title %}Department Detail{% endblock title %}

{% block content %}

<h3 class="cover-heading">{{ department.name }} Department</h3>
<br>

<p class="lead"><u>Employees</u></p>
{% for employee in department.employees.all %}
    <p class="lead">{{ employee.name }}</p>
{% endfor %}
<a class="btn btn-link" href="{% url 'app:departments' %}">Back</a>

{% endblock content %}

django/practice_project/config/app/templates/app/department_list.html
{% extends 'app/base.html' %}

{% block title %}Departments{% endblock title %}

{% block content %}

<h2 class="cover-heading">Here is a list of our departments</h2>
<div class="table-responsive">
    <table class="table table-sm">
        <caption>List of Departments</caption>
        <thead>
        <tr>
            <th scope="col">Department ID#</th>
            <th scope="col">Name</th>
            <th scope="col">Employees</th>
        </tr>
        </thead>
        <tbody>
        {% for department in departments %}
        <tr>
            <td>{{ department.id }}</td>
            <td><a href="{% url 'app:department' pk=department.id %}">{{ department.name }}</a></td>
            <td>{{ department.employees.count }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

django/practice_project/config/app/templates/app/employee_confirm_delete.html
{% extends 'app/base.html' %}

{% block title %} Confirm Delete {% endblock title %}

{% block content %}
<h1>Delete {{ employee.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-link" value="Delete">
    <a class="btn btn-link" href="{% url 'app:employee' pk=employee.pk  %}">Cancel</a>
</form>
<br>
<p></p>

{% endblock content %}

django/practice_project/config/app/templates/app/employee_detail.html
{% extends 'app/base.html' %}

{% block title %}Employee Detail{% endblock title %}

{% block content %}

<h3 class="cover-heading">{{ employee.name }}'s Details</h3>
<br>
<p class="lead"><u>Email</u></p>
<p class="lead">{{ employee.email }}</p>
<p class="lead"><u>Phone</u></p>
<p class="lead">{{ employee.phone }}</p>
<p class="lead"><u>Department</u></p>
<p class="lead">{{ employee.department }}</p>
<a class="btn btn-link" href="{% url 'app:update' pk=employee.id %}">Edit</a>
<a class="btn btn-link" href="{% url 'app:delete' pk=employee.id %}">Delete</a>

{% endblock content %}

django/practice_project/config/app/templates/app/employee_form.html
{% extends 'app/base.html' %}

{% block title %}Employee Form{% endblock title %}

{% block content %}

<h3 class="cover-heading">
{% if not form.instance.pk %}
Create Employee
{% else %}
Update Employee
{% endif %}
</h3>

<br>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" value="Submit">
  <a class="btn btn-link" href="{% url 'app:employee' pk=employee.pk  %}">Cancel</a>
</form>

{% endblock content %}

django/practice_project/config/app/templates/app/employee_list.html
{% extends 'app/base.html' %}

{% block title %}Employees{% endblock title %}

{% block content %}

<h2 class="cover-heading">Here is a list of our employees</h2>
<div class="table-responsive">
    <table class="table table-sm">
        <caption>List of employees</caption>
        <thead>
        <tr>
            <th scope="col">Employee ID#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Department</th>
        </tr>
        </thead>
        <tbody>
        {% for employee in employees %}
        <tr>
            <td>{{ employee.id }}</td>
            <td><a href="{% url 'app:employee' pk=employee.id %}">{{ employee.name }}</a></td>
            <td>{{ employee.email }}</td>
            <td>{{ employee.phone }}</td>
            <td>{{ employee.department }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

django/practice_project/config/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="text-center">

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand"><a class="nav-link active" href="{% url 'home' %}">DJANGO</a></h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="{% url 'app:employees' %}">Employees</a>
                <a class="nav-link" href="{% url 'app:departments' %}">Departments</a>
                <a class="nav-link" href="#">Login</a>
                <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>
            </nav>
        </div>
    </header>
    <main role="main" class="inner cover">
        {% block content %}

        {% endblock content %}
    </main>
    <footer class="mastfoot mt-auto">
        <div class="inner">
            <p>Developed by <a href="http://mmaruf.herokuapp.com/" target="_blank">Maruf</a>.</p>
        </div>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

django/practice_project/config/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<h1 class="cover-heading">Hi!</h1>
<p class="lead">This is just basic DJANGO project practice.</p>
<h3 class="cover-heading">{{ home_desc }}</h3>

{% endblock content %}